# SLAM 建图参数
slam_toolbox:
  ros__parameters:
    mode: mapping                # 建图模式
    scan_topic: /scan
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint   
    resolution: 0.05
    max_laser_range: 12.0        # 雷达实际量程
    map_update_interval: 1.0     # 1 秒一帧地图
    minimum_time_interval: 0.5
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
