<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_gazebo</name>
  <version>0.0.0</version>
  <description>A Gazebo Nav car base on ROS2.</description>
  <maintainer email="panqiyu521@gmail.com">Kirin Pan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>robot_description</exec_depend>

  <!-- <exec_depend>geometry_msgs</exec_depend> -->
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>

  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>diff_drive_controller</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>


  <depend>geometry_msgs</depend>

  <depend>ros-jazzy-ros-gz-sim</depend>
  <depend>ros-jazzy-ros-gz-bridge</depend>

  <depend>ros-jazzy-ros2-control</depend>
  <depend>ros-jazzy-ros2-controller-manager</depend>
  <depend>ros-jazzy-diff-drive-controller</depend>
  <depend>ros-jazzy-joint-state-broadcaster</depend>
  <depend>ros-jazzy-gz-ros-control</depend>

  <depend>ros-jazzy-navigation2</depend>
  <depend>ros-jazzy-nav2-bringup</depend>

  <depend>ros-jazzy-slam-toolbox</depend>
  <depend>ros-jazzy-slam-toolbox</depend>
  <depend>ros-jazzy-teleop-twist-keyboard</depend>


  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
